### PR TITLE
Pass global params

### PR DESCRIPTION
**Pull request by edubacco**
I've tried to use the import feature with the --skip-plugins global param. I've noted that this arguments (as every global argument) it's not passed to the internal calls to wp-cli.
This PR passes to WP_CLI::launch_self() the correct global parameters.

### CODE REVIEW

**Comment by nicholasio** [comment]
`launch_self` should pass the global parameters automatically. Are you saying that there's a subset of them that are not passed?

**Comment by edubacco** [comment]
I'm pretty new with wp-cli development, but I'm sure that --skip-plugins is not passed as a global params.
Looking at https://github.com/wp-cli/wp-cli/blob/master/php/class-wp-cli.php#L990 , it seems that only `path`, `url`, `user`, `allow-root`, are passed as global, not all global params (https://make.wordpress.org/cli/handbook/config/#global-parameters). In my PR, I'm passing all params manually

**Comment by nicholasio** [comment]
Ok, I'll take a look at this. There might be a reason they're not passed.

**Comment by jeffpaul** [comment]
@nicholasio any updates from your review here?

**Pull request closed without merging**
